# Generated by Django 5.1.13 on 2025-11-03 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ITV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('fecha_revision', models.DateField()),
                ('valido_hasta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('pais_origen', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anyo_lanzamiento', models.PositiveIntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coches', to='examenJuan.fabrica')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coches', to='examenJuan.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('kilometraje', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('aprobada', models.BooleanField(default=False)),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='examenJuan.coche')),
                ('itv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones', to='examenJuan.itv')),
            ],
        ),
    ]
