# Generated by Django 5.1.13 on 2025-11-03 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenJuan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coche',
            name='color',
        ),
        migrations.RemoveField(
            model_name='coche',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='coche',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='fabrica',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='fabrica',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='itv',
            name='centro',
        ),
        migrations.RemoveField(
            model_name='itv',
            name='fecha_revision',
        ),
        migrations.RemoveField(
            model_name='itv',
            name='valido_hasta',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='pais_origen',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='aprobada',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='coche',
            name='itv',
            field=models.ManyToManyField(through='examenJuan.Revision', to='examenJuan.itv'),
        ),
        migrations.AlterField(
            model_name='coche',
            name='fabrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenJuan.fabrica'),
        ),
        migrations.AlterField(
            model_name='coche',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenJuan.marca'),
        ),
        migrations.AlterField(
            model_name='coche',
            name='precio_base',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='revision',
            name='coche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenJuan.coche'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='itv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examenJuan.itv'),
        ),
    ]
